### ISSUE TITLE
Support for PotentialActions

### ISSUE THREAD

**Issue by nmaupu** [atc0005/go-teams-notify#102]
Hi !

Is there any plan to support _potential actions_ in MessageCards as per https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using ?

**Comment by atc0005** [comment]
In short, it would be a useful feature to include, but I don't have anything lined up at present. I've got some obligations in front of me that would prevent me from working on this directly, but Pull Requests are welcome.

---

I took a stab at this around March 2020, but ran into a few walls when doing so. It's been long enough now that I only have a vague sense of the issues. I dug back through some prototype branches and I see where I stubbed out the beginnings of the work, but I didn't get far:

https://github.com/atc0005/go-teams-notify/blob/test-extended-messagecard-type/messagecard.go

This is back before I worked to cleanup the prototype code and get it ready for inclusion in the `dasrick/go-teams-notify` repo.

**Comment by nmaupu** [comment]
Here you go: #103

**Comment by atc0005** [comment]
@nmaupu Thanks. I'm looking over it. It also looks like GitHub has recently changed how workflows are handled for forks. Instead of running automatically as before, I had to "approve" them first.

**Comment by atc0005** [comment]
Current thinking:

1. GH-103 is the first big effort at this, completing most of the work needed to add the support. I'll plan to merge soon as-is.
1. I'll create a new PR to fix linting errors and and merge
1. I'll create a new PR to add some additional support that I've (temporarily) bundled locally in a project of mine
1. I'll work on documentation updates, including a new example that showcases the extended functionality
1. Update CHANGELOG
1. Tag & publish new release

I estimate releasing the new version within a week, hopefully within the next few days.

**Comment by atc0005** [comment]
> 3\. I'll create a new PR to add some additional support that I've (temporarily) bundled locally in a project of mine

TODO (note to self, pulled from https://github.com/atc0005/go-teams-notify/pull/103#issuecomment-827525301):

- make sure that this includes validation for the allowed number of `potentialAction` property entries
  - this applies to adding the `potentialAction` property entries to the main card and to sections
- confirm (I don't recall either way) that the `OpenUri` action `targets` field values are validated
  - currently only four values are supported, others should be rejected
- review other actions and determine where validation can be applied

**Comment by atc0005** [comment]
Validation work appears to be the next step.

Unordered thoughts:

- The `NewMessageCardPotentialAction` function is one potential hook to validate provided `potentialActionType` values provided (only 4 are supported)
- `MessageCardSection.AddPotentialAction()` is one potential hook to validate the total number of provided actions
  - 4 per collection are allowed
- `MessageCard.AddPotentialAction()` ...
  - as with `MessageCardSection.AddPotentialAction()`, 4 per collection are allowed

**Comment by atc0005** [comment]
> * The `NewMessageCardPotentialAction` function is one potential hook to validate provided `potentialActionType` values provided (only 4 are supported)

Currently the function definition does not return an error, so we'd have to modify that. Since a tagged release hasn't been made yet, I feel that we can do so without violating semantic versioning.
