### ISSUE TITLE
Add `Adaptive Card` message format support

### ISSUE THREAD

**Issue by atc0005** [atc0005/go-teams-notify#157]
I've not fully explored it, but as part of the initial work for GH-127 I learned that it *appears* to support both user mentions and existing functionality provided by the legacy `MessageCard` format.

Initial support for this format would unify the functionality currently provided (separately) by the `messagecard` and `botapi` packages.

**Comment by atc0005** [comment]
Minimum implementation example:

https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#send-adaptive-cards-using-an-incoming-webhook

**Comment by atc0005** [comment]
> Minimum implementation example:
> 
> https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#send-adaptive-cards-using-an-incoming-webhook

Maybe not. Attempting to use this results in this error:

> `Summary or Text is required.`

I've seen multiple references to a requirement that the card is wrapped as an "attachment".

This appears to work:

```json
{
    "type": "message",
    "attachments": [
        {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "contentUrl": null,
            "content": {
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard",
                "version": "1.2",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "Hi <at>John Doe</at>"
                    }
                ],
                "msteams": {
                    "entities": [
                        {
                            "type": "mention",
                            "text": "<at>John Doe</at>",
                            "mentioned": {
                                "id": "29:123124124124",
                                "name": "John Doe"
                            }
                        }
                    ]
                }
            }
        }
    ]
}
```

but places the text within a "box":

<img width="534" alt="image" src="https://user-images.githubusercontent.com/36716992/157645483-1ba55355-6301-46e8-a379-0fdbec4125ad.png">

refs https://stackoverflow.com/questions/50753072/microsoft-teams-webhook-generating-400-for-adaptive-card

**Comment by atc0005** [comment]
> but places the text within a "box":
> 
> <img alt="image" width="534" src="https://user-images.githubusercontent.com/36716992/157645483-1ba55355-6301-46e8-a379-0fdbec4125ad.png">

After comparing against earlier test messages, this looks to be normal; I'm likely just not used to seeing a minimal implementation like we're starting with here.

**Comment by atc0005** [comment]
Looks like version 1.3 of the Adaptive Card format is the highest version supported (at present) by Microsoft Teams for user generated messages.

**Comment by atc0005** [comment]
> Looks like version 1.3 of the Adaptive Card format is the highest version supported (at present) by Microsoft Teams for user generated messages.

Inconclusive. Per https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference, Adaptive Card schema v1.4 or earlier is supported if the card is sent via bot or action based messaging extension.

It's unclear where incoming webhooks fall.

**Comment by atc0005** [comment]
> > Looks like version 1.3 of the Adaptive Card format is the highest version supported (at present) by Microsoft Teams for user generated messages.
> 
> Inconclusive. Per https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference, Adaptive Card schema v1.4 or earlier is supported if the card is sent via bot or action based messaging extension.
> 
> It's unclear where incoming webhooks fall.

Using https://adaptivecards.io/designer and setting `host app` to `Microsoft Teams - Dark` with the `Target version` set to 1.4 or higher results in this warning:

> [Warning] The selected Target Version (1.4) is only supported by bot sent card. For user sent cards please use version 1.3

<img alt="max supported Adaptive Card schema version for Microsoft Teams" src="https://user-images.githubusercontent.com/36716992/161031824-69c8c3c9-6909-40ed-83d2-c5fa19ccaf81.png">

Looks like 1.3 might be the max supported version after all.

**Comment by atc0005** [comment]
Setting `Target version` to 1.5 confirms explicitly that version 1.5 is not supported:

> [Warning] The selected Target Version (1.5) is greater than the version supported by Microsoft Teams - Dark (1.4)

**Comment by atc0005** [comment]
Some definite drawbacks of using an Adaptive Card vs the legacy MessageCard, formatting in particular:

> The following Markdown tags are not supported:
> 
> - Headers
> - Tables
> - Images
> - Preformatted text
> - Blockquotes

The last two I personally relied upon when pushing formatted log messages or error messages from monitoring systems into Teams channels.

Will need to annotate the formatting functionality sufficiently to indicate that it's intended for use with MessageCard text and not text intended for Adaptive Cards.

refs https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format#format-cards-with-markdown

**Comment by atc0005** [comment]
Beginning initial polish phase.

**Comment by atc0005** [comment]
> Will need to annotate the formatting functionality sufficiently to indicate that it's intended for use with MessageCard text and not text intended for Adaptive Cards.

Ended up "moving" the functionality into the `messagecard` package, marking the existing functions as deprecated.

**Comment by atc0005** [comment]
GH-162 adds the first usable implementation of the new package. Unstable/dev release v2.7.0-alpha.2 provides that functionality for general review & feedback.

This should resolve atc0005/send2teams#225 and provide a starting point for GH-127.

**Comment by atc0005** [comment]
I've closed GH-127 and marked it as resolved (no negative feedback received since I noted the new support two months back).

I plan to focus on linting errors surfaced from recent PRs, then tag a release candidate shortly after.

**Comment by atc0005** [comment]
> I plan to focus on linting errors surfaced from recent PRs, then tag a release candidate shortly after.

Output from the most recent PR submitted by dependabot:

```
2022-06-30T07:06:12.4003785Z Running golangci-lint ...
2022-06-30T07:06:13.4179543Z level=warning msg="[runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'."
2022-06-30T07:06:18.1993072Z adaptivecard/adaptivecard.go:1089:1: cognitive complexity 46 of func `(Element).Validate` is high (> 10) (gocognit)
2022-06-30T07:06:18.1993890Z func (e Element) Validate() error {
2022-06-30T07:06:18.1994211Z ^
2022-06-30T07:06:18.1994668Z adaptivecard/adaptivecard.go:938:1: cognitive complexity 29 of func `(Card).Validate` is high (> 10) (gocognit)
2022-06-30T07:06:18.1995138Z func (c Card) Validate() error {
2022-06-30T07:06:18.1995857Z ^
2022-06-30T07:06:18.1996429Z adaptivecard/adaptivecard.go:1262:1: cognitive complexity 15 of func `(Column).Validate` is high (> 10) (gocognit)
2022-06-30T07:06:18.1996866Z func (c Column) Validate() error {
2022-06-30T07:06:18.1997349Z ^
2022-06-30T07:06:18.1997759Z adaptivecard/adaptivecard.go:1412:1: cognitive complexity 11 of func `(Action).Validate` is high (> 10) (gocognit)
2022-06-30T07:06:18.1998213Z func (a Action) Validate() error {
2022-06-30T07:06:18.1998515Z ^
2022-06-30T07:06:18.2093458Z make: *** [Makefile:59: linting] Error 1
2022-06-30T07:06:18.2156015Z ##[error]Process completed with exit code 2.
```

**Comment by atc0005** [comment]
Initial implementation complete. Further polishing is needed, but will focus on that in the next release.

**Comment by qris** [comment]
> > The following Markdown tags are not supported:
> > 
> > * Preformatted text
> 
> The last two I personally relied upon when pushing formatted log messages or error messages from monitoring systems into Teams channels.

You can now use [CodeBlock](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html#codeblock-in-adaptive-cards) instead of TextBlock for preformatted text with syntax highlighting in AdaptiveCards, although it's not yet documented in the [AdaptiveCard Explorer](https://adaptivecards.io/explorer/).

**Comment by atc0005** [comment]
@qris Acknowledged.

Recent activity:

- https://github.com/atc0005/go-teams-notify/pull/293
- https://github.com/atc0005/go-teams-notify/pull/298
- https://github.com/microsoft/AdaptiveCards/issues/8927

and:

- https://github.com/microsoft/AdaptiveCards/issues/9004
  - I see that you submitted this, but wanted to link to it here for anyone else coming across this GH issue in the future
