### ISSUE TITLE
Wrong json key name for URL (uses uri insted)

### ISSUE THREAD

**Issue by janfonas** [atc0005/go-teams-notify#179]
I've been trying to add an image to a message, but failing. Did a `prettyPrint()` of the json, and I see that the `url` key is missing, but it does have  a `uri` key, with the value from `Url` in my code. Looking at the docs from MS, I think this should be `url`.

https://github.com/atc0005/go-teams-notify/blob/9b58fcec0b720b93330e9a04a8e1db5a3617eb2c/adaptivecard/adaptivecard.go#L481

Should not this be `json:"url,omitempty"` and not `json:"uri,omitempty"`

**Comment by atc0005** [comment]
> Looking at the docs from MS, I think this should be `url`.

Thank you for the report, and it looks like you're right:
https://adaptivecards.io/explorer/Image.html

> Properties
> url
> 
> The URL to the image. Supports data URI in version 1.2+
> 
>     Type: uri
>     Required: Yes

I'll fix this momentarily.

**Comment by atc0005** [comment]
@janfonas Pushing tag `v2.7.0-alpha.6` now with the changes from #180.

**Comment by janfonas** [comment]
Great! Working like a charm! Thanks for the quick response! :)

**Comment by atc0005** [comment]
@janfonas You're welcome. Thanks for taking the time to file a report, it is much appreciated!
