### ISSUE TITLE
Use proxy for http client?

### ISSUE THREAD

**Issue by ahfa92** [atc0005/go-teams-notify#240]
How can we use proxy server for this package?

In an environment which is very strict, we can not simply use http_proxy for global application. Is there any way to route the url via proxy server e.g. squid proxy?

Thank you in advance!!

**Comment by atc0005** [comment]
Hi @ahfa92,

I've not tried that before, but I found what I think is a good explanation here:

- https://stackoverflow.com/a/14663620/903870

Here is an untested example based on the existing [adaptivecard/basic example](https://github.com/atc0005/go-teams-notify/blob/429c5ce12513b694b6354435da03d181bd465151/examples/adaptivecard/basic/main.go):

```golang
package main

import (
	"log"
	"net/http"
	"net/url"
	"os"

	goteamsnotify "github.com/atc0005/go-teams-notify/v2"
	"github.com/atc0005/go-teams-notify/v2/adaptivecard"
)

func main() {

	// Initialize a new Microsoft Teams client.
	mstClient := goteamsnotify.NewTeamsClient()

	proxyURLString := "http://proxyIp:proxyPort"
	proxyUrl, err := url.Parse(proxyURLString)

	if err != nil {
		log.Printf(
			"failed to parse proxy URL %q: %v",
			proxyURLString,
			err,
		)
		os.Exit(1)
	}

	httpClient := mstClient.HTTPClient()
	httpClient.Transport = &http.Transport{Proxy: http.ProxyURL(proxyUrl)}

	// Set webhook url.
	webhookUrl := "https://outlook.office.com/webhook/YOUR_WEBHOOK_URL_OF_TEAMS_CHANNEL"

	// The title for message (first TextBlock element).
	msgTitle := "Hello world"

	// Formatted message body.
	msgText := "Here are some examples of formatted stuff like " +
		"\n * this list itself  \n * **bold** \n * *italic* \n * ***bolditalic***"

	// Create message using provided formatted title and text.
	msg, err := adaptivecard.NewSimpleMessage(msgText, msgTitle, true)
	if err != nil {
		log.Printf(
			"failed to create message: %v",
			err,
		)
		os.Exit(1)
	}

	// Send the message with default timeout/retry settings.
	if err := mstClient.Send(webhookUrl, msg); err != nil {
		log.Printf(
			"failed to send message: %v",
			err,
		)
		os.Exit(1)
	}
}
```

Feedback is welcome.

**Comment by ahfa92** [comment]
I will try to use this method. Will inform you later. Thanks!

**Comment by ahfa92** [comment]
Sorry for asking again.

If I use these codes:
`func main() {
	// Initialize a new Microsoft Teams client.
	mstClient := goteamsnotify.NewTeamsClient()

	proxyURLString := "http://proxyIp:proxyPort"
	proxyUrl, err := url.Parse(proxyURLString)

	// Create a copy of the default mstClient.HTTPClient
	fallbackHTTPClient := mstClient.HTTPClient()

	if err == nil {
		fallbackHTTPClient.Transport = &http.Transport{Proxy: http.ProxyURL(proxyUrl)}
	} else {
		log.Printf(
			"Failed to parse proxy URL %q: %v. Using the default HTTP client without a proxy.",
			proxyURLString,
			err,
		)
	}

	// Set webhook URL.
	webhookUrl := "https://outlook.office.com/webhook/YOUR_WEBHOOK_URL_OF_TEAMS_CHANNEL"

	// The title for the message (first TextBlock element).
	msgTitle := "Hello world"

	// Formatted message body.
	msgText := "Here are some examples of formatted stuff like " +
		"\n * this list itself  \n * **bold** \n * *italic* \n * ***bolditalic***"

	// Create a message using the provided formatted title and text.
	msg, err := adaptivecard.NewSimpleMessage(msgText, msgTitle, true)
	if err != nil {
		log.Printf(
			"Failed to create message: %v",
			err,
		)
		os.Exit(1)
	}

	// Send the message with the configured HTTP client.
	mstClient.HTTPClient = fallbackHTTPClient
	if err := mstClient.Send(webhookUrl, msg); err != nil {
		log.Printf(
			"Failed to send message: %v",
			err,
		)
		os.Exit(1)
	}
}`

Will that work?

**Comment by ahfa92** [comment]
The solution is working. Thank you!!
