### ISSUE TITLE
Private teamsMessage Type in SendWithContext Method

### ISSUE THREAD

**Issue by nikoksr** [atc0005/go-teams-notify#285]
Hi there, [notify](https://github.com/nikoksr/notify) author here! We've been in contact before about a similar [issue](https://github.com/nikoksr/notify/pull/488#issuecomment-1479413765). 

A recently opened, very friendly [issue](https://github.com/nikoksr/notify/issues/839) in Notify brought to my attention that the O365 connectors within Teams will be deprecated. Since notify is still using deprecated members of your library like `goteamsnotify.MessageCard`, I began with fixing this. While doing so I noticed some issues when trying to abstract the `SendWithContext` method.

## The Issue

```go
func (*goteamsnotify.TeamsClient) SendWithContext(ctx context.Context, webhookURL string, message goteamsnotify.teamsMessage) error
```

`goteamsnotify.teamsMessage` appears to be a private type.

## Impact on Notify

The main problem we're facing is that we can no longer abstract and mock the teams library due to the private `teamsMessage` type. This is particularly important for Notify because we rely heavily on mocking for our testing strategy. With over 30 external messaging platforms integrated into Notify, conducting end-to-end tests for each one isn't feasible. Mocking allows us to effectively test our integrations without the need for actual external connections.

This is the interface we used to use to abstract your teams library in Notify:

```go
type teamsClient interface {
	SendWithContext(ctx context.Context, webhookURL string, webhookMessage teams.MessageCard) error
	SkipWebhookURLValidationOnSend(skip bool) teams.API
}
```

Now, if switching to the latest state of `go-teams-notify`, we'd have to do this:

```go
type teamsClient interface {
	SendWithContext(ctx context.Context, webhookURL string, webhookMessage teams.teamsMessage) error
	SkipWebhookURLValidationOnSend(skip bool) *teams.TeamsClient
}
```

And at that point, we're trying to externally access a private member of your library which of course leads to a compile-time error:

```text
compiler: teamsMessage not exported by package goteamsnotify
```

While we could add a whole wrapper layer in Notify around your library to work around this issue, it would introduce a lot of complexity and make maintenance more challenging. I'd really like not to.

## Possible Solutions

- Make `teamsMessage` public
- Write a teams wrapper in Notify

---

Please let me know if there's anything unclear and thank you for your continued maintenance of this project. 

Cheers,
Niko

**Comment by atc0005** [comment]
Hi @nikoksr,

> Possible Solutions: 
> * Make `teamsMessage` public

I'm interested in testing that change.

For your project, what command do you run to regenerate the mocks for the `service/msteams` files?

I'm not familiar with `mockery` and want to make sure I'm following the same steps that you would.

I see how you have it listed [here](https://github.com/nikoksr/notify/blob/851f661d1ccd23f478a9fa70e74b4342b0ce0180/service/amazonsns/amazon_sns.go#L15):

```go
//go:generate mockery --name=snsSendMessageAPI --output=. --case=underscore --inpackage
```
but since I don't see the same [here](https://github.com/nikoksr/notify/blob/851f661d1ccd23f478a9fa70e74b4342b0ce0180/service/msteams/ms_teams.go#L11):

```go
type teamsClient interface {
// ...
```

I wasn't sure if that indicated that you handcrafted the file or if I was just overlooking something.

From what I can tell I can see that [this](https://github.com/nikoksr/notify/blob/851f661d1ccd23f478a9fa70e74b4342b0ce0180/service/msteams/mock_teams_client.go#L1) file is generated, so I just assumed that I was overlooking the steps for generating it.

**Comment by nikoksr** [comment]
@atc0005 thanks for the quick response. 

Nice catch, that's got to be a leftover because I thought I had removed all those go:generate directives. We recently upgraded to the latest version of mockery which uses a config based approach (you can see the config at the root of the repo). Running `make mock` should be sufficient to (re)generate the mocks. 

Let me know if there's anything else, I can help you with.

**Comment by atc0005** [comment]
@nikoksr 

Thanks for that. I ran `make mock` in a test branch to regenerate the mocks. Ran it several times as I fumbled about. :)

Test changes here in a fork of your repo:

- https://github.com/atc0005/nikoksr.notify/commits/prototyping-msteams-changes/

For simplicity I did the following:

- vendored all dependencies
- updated mockery config to exclude `vendor` directory
- directly modified `vendor/github.com/atc0005/go-teams-notify` content
  - expose `teamsMessage` as `TeamsMessage`
    - https://github.com/atc0005/nikoksr.notify/commit/2c07913c1c132b9a2668ad76d04e0fb855d66a08#diff-1a846122533d2dfbd13a1b361fd6c2b4793cac5245d95db13d927770b11fd6e4
- updated files in notify project
  - `service/msteams/ms_teams.go`
    - primarily https://github.com/atc0005/nikoksr.notify/commit/4c9fd641a31bdcaeac421c424a69617aa3819d80#diff-39f2fd9835038c496c3d3f1e08a577472e63060e9deb76b4ea0d5218298470c5
    - minor https://github.com/atc0005/nikoksr.notify/commit/691a9fe7ceda7ce054741a11ec2d4f080d793eec#diff-39f2fd9835038c496c3d3f1e08a577472e63060e9deb76b4ea0d5218298470c5
  - `service/msteams/ms_teams_test.go`
    - primarily https://github.com/atc0005/nikoksr.notify/commit/691a9fe7ceda7ce054741a11ec2d4f080d793eec#diff-0dd4e5e7ab916dd33416c03444adb0592b8a49c8b114dfebff0ee817cfa82489

The commits are messy (some unrelated changes included), log messages not so great, etc.

I tried to deep link directly to relevant bits.

After all changes the tests pass:

```console
$ go test -v ./service/msteams/
=== RUN   TestMSTeams_Send
=== PAUSE TestMSTeams_Send
=== CONT  TestMSTeams_Send
=== RUN   TestMSTeams_Send/Successful_send_to_single_webhook
=== PAUSE TestMSTeams_Send/Successful_send_to_single_webhook
=== RUN   TestMSTeams_Send/Successful_send_to_multiple_webhooks
=== PAUSE TestMSTeams_Send/Successful_send_to_multiple_webhooks
=== RUN   TestMSTeams_Send/Teams_client_error
=== PAUSE TestMSTeams_Send/Teams_client_error
=== CONT  TestMSTeams_Send/Successful_send_to_single_webhook
=== CONT  TestMSTeams_Send/Teams_client_error
=== CONT  TestMSTeams_Send/Successful_send_to_multiple_webhooks
--- PASS: TestMSTeams_Send (0.00s)
    --- PASS: TestMSTeams_Send/Teams_client_error (0.00s)
    --- PASS: TestMSTeams_Send/Successful_send_to_single_webhook (0.00s)
    --- PASS: TestMSTeams_Send/Successful_send_to_multiple_webhooks (0.00s)
PASS
ok      github.com/nikoksr/notify/service/msteams       0.010s
```

From what I can tell exporting `TeamsMessage` (without its internals) is enough to make this work. Feedback is welcome.

If nothing further needs adjusting in this project I'll plan to release that change as a follow-up (e.g., v2.12.0) to the upcoming v2.11.0 release.

**Comment by nikoksr** [comment]
Hi @atc0005, you went above and beyond with that, thank you so much. 

Sounds great! Do I see it correctly that there's nothing I need to explicitly do to fix [this issue](https://github.com/nikoksr/notify/issues/839)? I'll refactor Notify's teams service accordingly once `v2.12.0` is live, which will remove all the deprecated bits of your library that we're still using. There's nothing I need to add for it to support workflow hooks, right?  

I checked this [PR](https://github.com/atc0005/go-teams-notify/pull/275) of yours and from what I can tell, the most breaking thing that changes is the URL pattern validation. Which would make this more of a user concern than mine, if I understand it correctly.

**Comment by atc0005** [comment]
Hi @nikoksr,

> you went above and beyond with that, thank you so much

You're welcome.

> the most breaking thing that changes is the URL pattern validation

Perhaps you didn't mean it that way, but I'd argue that's not a breaking change. The previous pattern validation behavior continues to work as before, only now an additional default pattern is applied to permit workflow connector URLs to validate alongside O365 connector URLs.

> Do I see it correctly that there's nothing I need to explicitly do to fix https://github.com/nikoksr/notify/issues/839? I'll refactor Notify's teams service accordingly once v2.12.0 is live

Now that you've looked over the changes and don't see any glaring omissions, I'll proceed with applying the necessary changes to the development branch and tag a pre-release so you and others can test further (if desired).

Thanks for the feedback.

**Comment by atc0005** [comment]
> I'll proceed with applying the necessary changes to the development branch and tag a pre-release so you and others can test further (if desired).

@nikoksr,

New tag:

- https://github.com/atc0005/go-teams-notify/releases/tag/v2.12.0-alpha.1

**Comment by nikoksr** [comment]
Created a PR in Notify where I successfully implemented the fixed teams service using [v2.12.0-alpha.1](https://github.com/atc0005/go-teams-notify/releases/tag/v2.12.0-alpha.1). Will merge once it gets fully released. 

Please let me know if there's anything left to clarify. And thanks again for your quick help, Adam :)

**Comment by atc0005** [comment]
@nikoksr,

You're welcome.

Thanks for the CC on that PR. It was good to see the full set of needed changes.

Created a RC tag to invite/encourage feedback from others before tagging a stable release:

- https://github.com/atc0005/go-teams-notify/releases/tag/v2.12.0-rc.1

**Comment by atc0005** [comment]
@nikoksr new release:

- https://github.com/atc0005/go-teams-notify/releases/tag/v2.12.0
