### ISSUE TITLE
URLs

### ISSUE THREAD

**Issue by jason-costello** [atc0005/go-teams-notify#89]
The URLs I'm getting from our instance of Teams:

 https://teams.microsoft.com/l/channel/1111111111111000fffthread.tacv2/channel_name?groupId=uuid&tenantId=uuid

Hopefully I will have time at end of this week to get it added and make a pull request.

**Comment by jason-costello** [comment]
ignore me.  I was given the wrong links to work with.  They gave me links to the channel itself.  🤦

**Comment by atc0005** [comment]
@jason-costello no worries, thanks for your interest in this project!
